// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A legal document improvement AI agent.
 *
 * - improveLegalDocument - A function that handles the document improvement process.
 * - ImproveLegalDocumentInput - The input type for the improveLegalDocument function.
 * - ImproveLegalDocumentOutput - The return type for the improveLegalDocument function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveLegalDocumentInputSchema = z.object({
  documentText: z
    .string()
    .describe('The text content of the legal document to be improved.'),
});
export type ImproveLegalDocumentInput = z.infer<typeof ImproveLegalDocumentInputSchema>;

const ImproveLegalDocumentOutputSchema = z.object({
  improvedDocumentText: z
    .string()
    .describe('The improved text content of the legal document, incorporating AI suggestions.'),
  suggestions: z.array(z.string()).describe('A list of suggestions made by the AI.'),
});
export type ImproveLegalDocumentOutput = z.infer<typeof ImproveLegalDocumentOutputSchema>;

export async function improveLegalDocument(input: ImproveLegalDocumentInput): Promise<ImproveLegalDocumentOutput> {
  return improveLegalDocumentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveLegalDocumentPrompt',
  input: {schema: ImproveLegalDocumentInputSchema},
  output: {schema: ImproveLegalDocumentOutputSchema},
  prompt: `You are an expert legal assistant specializing in improving legal documents.

You will receive the text content of a legal document and provide suggestions for improving its accuracy, completeness, and legal soundness.

Document Text: {{{documentText}}}

Provide the improved document text and a list of suggestions made.`,
});

const improveLegalDocumentFlow = ai.defineFlow(
  {
    name: 'improveLegalDocumentFlow',
    inputSchema: ImproveLegalDocumentInputSchema,
    outputSchema: ImproveLegalDocumentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
